let stockProductos = 
[
    {
        id: 1, 
        nombre: "Lavandina", 
        precio: 79,
        cantidad: "1lt",
        img: 'public/img/lavandina.jpg',
        unidades: 1,
},
    {
        id: 2, 
        nombre: "Detergente", 
        precio: 79,
        cantidad: "5lts",
        img: 'public/img/detergente.jpg',
        unidades:1,
    },
    {
        id: 3, 
        nombre: "Pastillas de cloro para piscina", 
        precio: 199,
        cantidad: "x5 (1kg)",
        img: 'public/img/pastillas-cloro.jpg',
        unidades:1,
    },
    {
        id: 4, 
        nombre: "Jabón líquido para ropa", 
        precio: 179,
        cantidad: "1lt",
        img: 'public/img/jabon-liq.jpg',
        unidades:1,
    },
    {
        id: 5, 
        nombre: "Clarificador para piscina", 
        precio: 349,
        cantidad: "1lt",
        img: 'public/img/clarificador.jpg',
        unidades:1,
    },
    {
        id: 6, 
        nombre: "Alguicida para piscina", 
        precio: 349,
        cantidad: "1lt" ,
        img: 'public/img/alguicida.jpg',
        unidades:1,
    },
    {
        id: 7, 
        nombre: "Insecticida", 
        precio: 69,
        cantidad: "1lt" ,
        img: 'public/img/insecticida.jpg',
        unidades:1,
    },
    {
        id: 8, 
        nombre: "Fertilizante", 
        precio: 3499,
        cantidad: "10kg" ,
        img: 'public/img/fertilizante.jpg',
        unidades:1,
    },
]